services:
  ecommerce:
    container_name: ecommerce
    depends_on:
      - postgres_db
    build: .
    ports:
      - 8080:8080
    env_file: "docker.env"

  postgres_db:
    container_name: postgres_db
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 3366:5432
    env_file: "docker.env"
    

volumes:
  pgdata:
